language: go

env:
  - secure: "ACCvHWBVKddlUM5+fpTPsIM14At90jTXkUdhqDWJ8HKQvdQA33nBz1s6fq684S+/d1o1pPyhOTyqC3JVmMeOI8Dd07i+5ujAd/e5P7Zd3Bw1N/ZMO+rJylx73t+aYPJRog7sz4BAUPJS2Kn1/VZY4q6iS4Vx90kmgLNeTgkwwHo="

install:
  - mkdir -p ${GOPATH}/src/github.com/Juniper
  - (cd ${GOPATH}/src/github.com/Juniper && git clone https://github.com/Juniper/contrail-go-api -b 1.0.0)
  - wget https://github.com/Juniper/contrail-go-api/releases/download/1.0.0/contrail-go-api-generated-types-r2.20.tar.gz
  - tar -zxvf contrail-go-api-generated-types-r2.20.tar.gz -C ${GOPATH}/src
  - mkdir -p ${GOPATH}/src/github.com/GoogleCloudPlatform
  - (cd ${GOPATH}/src/github.com/GoogleCloudPlatform && git clone https://github.com/GoogleCloudPlatform/kubernetes.git -b v1.0.2)
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - GOPATH=${GOPATH}:${GOPATH}/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace

script:
  - go test -v -covermode=count -coverprofile=coverage.out github.com/Juniper/contrail-kubernetes/pkg/network/opencontrail
  - ${HOME}/gopath/bin/goveralls -service=travis-ci -repotoken ${COVERALLS_TOKEN} -package github.com/Juniper/contrail-kubernetes/pkg/network/opencontrail
